### PR TITLE
I add thanks for help

### PR DESCRIPTION
**Pull request by SeboPG**

### CODE REVIEW

**Comment by solbu** [comment]
What does this accomplish?

**Comment by andy5995** [comment]
Nothing.

**Comment by solbu** [comment]
Andy: I know that, but I wanted to hear his explanation. :-)

**Comment by SeboPG** [comment]
Hacktobreast 2018, sorry for this :-)

niedz., 7.10.2018, 04:53 użytkownik Johnny A. Solbu <
notifications@github.com> napisał:

**Pull request closed without merging**
